---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /etc/multipath:z
  labels:
    app: multipathd
  name: multipathd
spec:
  containers:
  - args:
    - kolla_start
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    image: quay.io/podified-antelope-centos9/openstack-multipathd@sha256:f0c544406fec8c01bd49727983124d5b43165b71667df2381d68669cf71b2c19
    name: multipathd
    securityContext:
      privileged: true
      procMount: Unmasked
    volumeMounts:
    - mountPath: /var/lib/iscsi
      name: var-lib-iscsi-host-0
    - mountPath: /etc/iscsi
      name: etc-iscsi-host-1
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: var-lib-kolla-config_files-multipathd.json-host-2
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: etc-pki-ca-trust-source-anchors-host-3
      readOnly: true
    - mountPath: /openstack
      name: var-lib-openstack-healthchecks-multipathd-host-4
      readOnly: true
    - mountPath: /dev
      name: dev-host-5
    - mountPath: /etc/multipath
      name: etc-multipath-host-6
    - mountPath: /etc/hosts
      name: etc-hosts-host-7
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: etc-pki-tls-certs-ca-bundle.trust.crt-host-8
      readOnly: true
    - mountPath: /etc/multipath.conf
      name: etc-multipath.conf-host-9
      readOnly: true
    - mountPath: /dev/log
      name: dev-log-host-10
    - mountPath: /lib/modules
      name: lib-modules-host-11
      readOnly: true
    - mountPath: /sys
      name: sys-host-12
    - mountPath: /run/udev
      name: run-udev-host-13
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: etc-pki-tls-certs-ca-bundle.crt-host-14
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: etc-pki-ca-trust-extracted-host-15
      readOnly: true
    - mountPath: /etc/localtime
      name: etc-localtime-host-16
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: etc-pki-tls-cert.pem-host-17
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/iscsi
      type: Directory
    name: var-lib-iscsi-host-0
  - hostPath:
      path: /etc/iscsi
      type: Directory
    name: etc-iscsi-host-1
  - hostPath:
      path: /var/lib/kolla/config_files/multipathd.json
      type: File
    name: var-lib-kolla-config_files-multipathd.json-host-2
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
      type: Directory
    name: etc-pki-ca-trust-source-anchors-host-3
  - hostPath:
      path: /var/lib/openstack/healthchecks/multipathd
      type: Directory
    name: var-lib-openstack-healthchecks-multipathd-host-4
  - hostPath:
      path: /dev
      type: Directory
    name: dev-host-5
  - hostPath:
      path: /etc/multipath
      type: Directory
    name: etc-multipath-host-6
  - hostPath:
      path: /etc/hosts
      type: File
    name: etc-hosts-host-7
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
      type: File
    name: etc-pki-tls-certs-ca-bundle.trust.crt-host-8
  - hostPath:
      path: /etc/multipath.conf
      type: File
    name: etc-multipath.conf-host-9
  - hostPath:
      path: /dev/log
      type: File
    name: dev-log-host-10
  - hostPath:
      path: /lib/modules
      type: Directory
    name: lib-modules-host-11
  - hostPath:
      path: /sys
      type: Directory
    name: sys-host-12
  - hostPath:
      path: /run/udev
      type: Directory
    name: run-udev-host-13
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
      type: File
    name: etc-pki-tls-certs-ca-bundle.crt-host-14
  - hostPath:
      path: /etc/pki/ca-trust/extracted
      type: Directory
    name: etc-pki-ca-trust-extracted-host-15
  - hostPath:
      path: /etc/localtime
      type: File
    name: etc-localtime-host-16
  - hostPath:
      path: /etc/pki/tls/cert.pem
      type: File
    name: etc-pki-tls-cert.pem-host-17
