FROM scratch
ARG IMAGE_NAME=edpm-hardened-uefi
ARG IMAGE_FILE=$IMAGE_NAME.qcow2
ARG CHECKSUM_FILE=$IMAGE_FILE.sha256

COPY $IMAGE_FILE .
COPY $CHECKSUM_FILE .

# Note: This file doesn't exist but is required to create a container which is never run.
CMD ["/bin/sh"]
