FROM scratch

ARG IMAGE_NAME=ironic-python-agent
ARG RAMDISK_FILE=$IMAGE_NAME.initramfs
ARG KERNEL_FILE=$IMAGE_NAME.kernel
ARG CHECKSUM_FILE=$IMAGE_NAME.sha256

COPY $RAMDISK_FILE .
COPY $KERNEL_FILE .
COPY $CHECKSUM_FILE .

# Note: This file doesn't exist but is required to create a container which is never run.
CMD ["/bin/sh"]
