FROM quay.io/centos-bootc/centos-bootc:stream9

RUN rm -rf /etc/yum.repos.d/*.repo
COPY output/yum.repos.d /etc/yum.repos.d

ARG PACKAGES="\
	bind-utils \
	buildah \
	cephadm \
	chrony \
	cloud-init \
	cronie \
	crudini \
	crypto-policies-scripts \
	device-mapper-multipath \
	driverctl \
	grubby \
	iproute-tc \
	iptables-services \
	iscsi-initiator-utils \
	jq \
	libvirt \
	libvirt-daemon-driver-qemu \
	lvm2 \
	nftables \
	numactl \
	openssh-server \
	openstack-network-scripts \
	openstack-selinux \
	openvswitch \
	os-net-config \
	podman \
	python3-libselinux \
	python3-pyroute2 \
	python3-pyyaml \
	rsync \
	tmpwatch \
	tuned-profiles-cpu-partitioning \
	sysstat"
ARG ENABLE_UNITS="openvswitch"

RUN dnf -y install $PACKAGES && dnf clean all && systemctl enable $ENABLE_UNITS

# Workaround openstack-network-scripts failing to run update-alternatives
# See https://issues.redhat.com/browse/OSPRH-13141
RUN ln -s /etc/sysconfig/network-scripts/ifup /usr/sbin/ifup
RUN ln -s /etc/sysconfig/network-scripts/ifdown /usr/sbin/ifdown

# Drop Ansible fact into place
COPY ansible-facts/bootc.fact /usr/etc/ansible/facts.d/bootc.fact
RUN chmod +x /usr/etc/ansible/facts.d/bootc.fact

# Template systemd service for services
COPY embedded-services/quadlets/systemd/service-template.kube /usr/share/containers/systemd/edpm-compute@.kube

## Service specific quadlets
COPY embedded-services/quadlets/*/* /usr/share/containers/systemd/

# Pre-cache containers for each service
RUN podman pull quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-iscsid:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-cron:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-multipathd:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified
RUN podman pull quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified
