#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]
[ -n "$TARGET_ROOT" ]

if [[ "amd64 x86_64" =~ "$ARCH" ]]; then
    ARCH="x86_64"
elif [[ "$ARCH" =~ (arm64|aarch64) ]]; then
    ARCH="aarch64"
elif [[ "ppc64le" =~ "$ARCH" ]]; then
    # We don't need to do anything here other than avoid the else clause
    :
else
    echo 'rhel root element only supports x86_64, aarch64 and ppc64le values for $ARCH'
    exit 1
fi

DIB_LOCAL_IMAGE=${DIB_LOCAL_IMAGE:-""}

if [ -n "$DIB_LOCAL_IMAGE" ]; then
    IMAGE_LOCATION=$DIB_LOCAL_IMAGE
    # No need to copy a local image into the cache directory, so just specify
    # the cached path as the original path.
    CACHED_IMAGE=$IMAGE_LOCATION
    BASE_IMAGE_FILE=`basename $DIB_LOCAL_IMAGE`
    BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
    CACHED_TAR=$DIB_IMAGE_CACHE/$BASE_IMAGE_TAR
    TAR_LOCK=$CACHED_TAR.lock
else
    echo "DIB_LOCAL_IMAGE is required"
    exit 1
fi

guestfish -v -x -i -a $CACHED_IMAGE <<EOF
tar-out / - numericowner:true xattrs:true | sudo tar -C $TARGET_ROOT --numeric-owner --xattrs --xattrs-include='*' --xattrs-exclude='security.selinux' -xf -
EOF
