#!/bin/bash
# These are useful, or at worst not harmful, for all images we build.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Overwrite the install-packages script to do nothing
cp $(which echo) $(which install-packages)
